## Practice along with class

***

## Math

***

$f(x) = x^2$

$\sum_{i=0}^{n-1} i$

$\bar{x} = \frac{\sum_{i=0}^{n-1} x_i} {n}$

In [12]:
type(123)

int

In [13]:
type(123.0)

float

## numpy

********

In [14]:
import numpy as np

In [15]:
L= np.array ([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

In [16]:
print (L)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
L.dtype

dtype('int32')

In [18]:
# Roll a die
rolls = np.random.randint(1, 7, 1000)

In [19]:
# Average roll.
np.mean(rolls)

3.537

In [20]:
# Spread
np.std(rolls)

1.748322338700733

In [21]:
# Likert Scale.
likert = np.random.randint(1, 8, 1000)

In [22]:
# Mode
np.mean(likert)

4.058

In [23]:
np.median(likert)

4.0

***

## END